### ISSUE TITLE
More props to customize the component

### ISSUE THREAD

**Issue by smakosh** [disqus/disqus-react#18]
We need more props to change the theme how ever we want.

**Comment by tterb** [comment]
@smakosh Currently themes are limited to light/dark color schemes and serif/sans-serif typeface, which can be configured in your site settings at `https://<your-shortname>.disqus.com/admin/settings/general/`. 

Though if you have an idea in mind, feel free to submit a PR.

**Comment by smakosh** [comment]
Yeah I was thinking of passing the theme as a prop, some websites that have a dark mode theme like mine, have to change the Disqus theme without the need of a window reload.

**Comment by tterb** [comment]
That's definitely an interesting idea.  
At this time we're primarily focused on bug-fixes/maintenance, but I'm going to leave this open for future contributions.

**Comment by sag1v** [comment]
Does `disqus` even support dynamic theme change? I inspected the `window.DISQUS` object and didn't see anything useful for changing it

**Comment by tterb** [comment]
@sag1v You're right, there isn't currently anything in the Disqus script for dynamically modifying the theme. Though if you'd like for Disqus to adapt to the dark/light themes for your site, this can accomplished by triggering the component to update after the theme change by passing the theme as a prop to the component.  
So for instance you could have something like this:  
```js
<Disqus.DiscussionEmbed shortname={disqusShortname} config={disqusConfig} theme={siteTheme} />
```
Where the `theme` that is being passed is the current dark/light state of your website.
That way when the website theme changes, the component will update and automatically determine whether the dark/light theme should be used.

**Comment by sag1v** [comment]
@tterb Not sure i follow.
You're saying that we can dynamically set the them?

```jsx
<Disqus.DiscussionEmbed shortname={disqusShortname} config={disqusConfig} theme='dark' />
```
This will set the theme to dark?

**Comment by tterb** [comment]
@sag1v Okay, I see what you mean.
My best advice in that case would be to defer passing the updated state to the `DiscussionEmbed` component until the transition completes, because as you mentioned the `embed.js` script that is used to load the embedded discussion doesn't currently support this functionality.

**Comment by sag1v** [comment]
Yeah this is what i ended up doing. I wish we had a better way of doing it though

```jsx
function Comments(props) {
  const [flipState, forceUpdate] = useState(false);
  const transitionEnd = useCallback((ev) => {
    const { target, propertyName } = ev;
    if (target === document.body && propertyName === 'background-color') {
      forceUpdate(o => !o);
    }
  }, [])

  useEffect(() => {
    document.body.addEventListener('transitionend', transitionEnd)
    return () => document.body.removeEventListener('transitionend', transitionEnd)
  }, [transitionEnd])

  return (
    <DiscussionEmbed {...props} fakeProp={flipState} />
  )
}
```

**Comment by tterb** [comment]
I'm going to close this issue since there isn't anything that can be done to further support this functionality within this package at this time, but I have added the provided explanation to the [FAQ page](https://github.com/disqus/disqus-react/wiki/Frequently-Asked-Questions) and I will pass on this feedback to the rest of the Disqus team so that we can aim to improve on this functionality in the future.
