### ISSUE TITLE
Loading non-stop

### ISSUE THREAD

**Issue by mateja176** [disqus/disqus-react#33]
### Describe the bug  
Non-stop loading

![Screenshot from 2019-07-02 23-38-11](https://user-images.githubusercontent.com/33357948/60548509-8bb73780-9d22-11e9-9f9d-2102a7affe12.png)

### To Reproduce  
  1. `git clone https://github.com/mateja176/react-hot-starter.git`  
  2. `cd react-hot-starter`
  3. `npm i`
  4. `npm start`
  5. `start http://localhost:3000/count`  

### Expected behavior  
Loading stops and comment count and discussion embed show up.

### Screenshots  

![Screenshot from 2019-07-02 23-46-28](https://user-images.githubusercontent.com/33357948/60548937-adfd8500-9d23-11e9-9e27-d64d934d7633.png)

![Screenshot from 2019-07-02 23-38-11](https://user-images.githubusercontent.com/33357948/60548669-f4061900-9d22-11e9-9138-32b913e72192.png)

### Specifications:  
 - OS: Linux, Ubuntu 19.04
 - Package version: 1.0.6
 - Node version: v11.14.0

**Comment by tterb** [comment]
@mateja176 Thanks for providing detailed steps to reproduce this issue. I'll look into this and try to help pinpoint the cause.

**Comment by tterb** [comment]
@mateja176 After removing the `process.env.NODE_ENV === 'production'` in order to load the Disqus component in the development environment, I received this error when attempting to reproduce this issue.   

![Screen Shot 2019-07-09 at 11 01 37 AM](https://user-images.githubusercontent.com/16360374/60912022-4ec6d580-a239-11e9-8afb-dea7855b5d88.png)

I was able to load the embedded discussion without any issues by providing a `url` and/or the `title` and `identifier` to the Disqus component.

ie: `<Disqus url={window.location.href} />` or `<Disqus title="count" identifier="count"/>`

Could you try this and see if that solves your issue?

**Comment by mateja176** [comment]
Thanks for having a thorough look. These are my findings based on your suggestion:

1. `<Disqus url={window.location.href} />`
  - Typescript throws an error since url is already provided in the Disqus component ( it's injected by the withRouter HOC )

2. `<Disqus title="count" identifier="count"/>`
  - Compiles without problems however the issue with the indeterminate disqus loader is still present

I've also logged the value of the disqus config to the console and everything seems normal. Moreover, I've created a branch named `disqus` containing changes mentioned in option two,

**Comment by mateja176** [comment]
To make things easier I've created a minimal reproduction [here](https://github.com/mateja176/disqus-demo)

**Comment by tterb** [comment]
Thanks for providing the reproduction repo. 
I cloned and ran the local server and again received the "We were unable to load Disqus" message. Though when I replaced the `const disqusShortname = 'react-hot-starter-dev';` with my own shortname, the embedded discussion loaded as intended.  

This leads me to believe that the issue may be caused by your Disqus configuration rather than a problem with the component, but I think we should be able to narrow it down with the following info:

  * Can you check that you have access to [https://react-hot-starter-dev.disqus.com/admin/settings/general/](https://react-hot-starter-dev.disqus.com/admin/settings/general/) and that the shortname matches?  
  * What is the URL that is associated with the shortname on Disqus? Do you have any [trusted domains](https://help.disqus.com/en/articles/1717206-how-to-use-trusted-domains) set?  
  * Have you tried providing the site URL that was registered on Disqus as the `url` attribute for the `disqusConfig`?

**Comment by mateja176** [comment]
> Thanks for providing the reproduction repo.
> I cloned and ran the local server and again received the "We were unable to load Disqus" message. Though when I replaced the `const disqusShortname = 'react-hot-starter-dev';` with my own shortname, the embedded discussion loaded as intended.
> 
> This leads me to believe that the issue may be caused by your Disqus configuration rather than a problem with the component, but I think we should be able to narrow it down with the following info:
> 
> * Can you check that you have access to https://react-hot-starter-dev.disqus.com/admin/settings/general/ and that the shortname matches?
> * What is the URL that is associated with the shortname on Disqus? Do you have any [trusted domains](https://help.disqus.com/en/articles/1717206-how-to-use-trusted-domains) set?
> * Have you tried providing the site URL that was registered on Disqus as the `url` attribute for the `disqusConfig`?

You were right! All that was necessary was to change the `url` property in the disqus config to the match the website url from the admin panel. Thank you so much for your help 🙏

**Comment by mateja176** [comment]
@tterb It may be good to document this piece of information for others not get stuck in the same place. Would you like me to create a PR documenting from where to get the `url` from?

**Comment by tterb** [comment]
@mateja176 I'm glad we were able to track down the problem!  
There's also an [alternative approach](https://help.disqus.com/en/articles/1717221-best-practices-for-staging-development-and-preview-sites) that is often recommended for staging/development, though some users prefer the simplicity of using the same URL for development and production.

I agree it would be beneficial to have these options documented somewhere in the package docs, so feel free to submit a PR.
