### ISSUE TITLE
A cookie associated with a cross-site resource at http://links.services.disqus.com/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by cs224** [disqus/disqus-react#45]
### Describe the bug  
I integrated the disqus-react component in my project and I get the console warning:
A cookie associated with a cross-site resource at http://links.services.disqus.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

### To Reproduce  
Simply integrate the disqus-react and use Chrome to browse the site and look at the dev-console.

### Expected behavior  
No warnings.

**Comment by tterb** [comment]
@cs224 Thanks for the report. We're currently tracking this issue internally as this warning needs to be addressed within the Disqus service, rather than the `disqus-react` package.

At this time, it shouldn't cause any unexpected behavior and is more of a way to spread the word and increase developer adoption of the `SameSite` attribute before the described behavior takes effect in 2020.

You can find more info about it here: [https://www.chromium.org/updates/same-site](https://www.chromium.org/updates/same-site)

**Comment by gaurav-mishra8** [comment]
Hello @tterb, I am also facing this issue. 
Has there been any change from chrome version 84+ ?

**Comment by tterb** [comment]
@gaurav-mishra8 I'm currently using Chrome v84.0.4147 and I am seeing some warnings about SameSite attribute but I'm not getting any messages saying any of them have been blocked.
Nonetheless, I will bring this up to the team so that we can investigate it further and keep it on our radar.

**Comment by jarodtaylor** [comment]
Looks to still be an issue in Chrome 85.
