### ISSUE TITLE
config is [object Object] when rendered to the DOM

### ISSUE THREAD

**Issue by mikecann** [disqus/disqus-react#89]
### Describe the bug  

It seems like the config object is being searialised into a HTML attribute

<img width="248" alt="chrome_v8OB8T7XOi" src="https://user-images.githubusercontent.com/215033/107848924-7a0ca000-6e32-11eb-8629-841e3c9d39f5.png">

Usage like: 

```
<DiscussionEmbed
              shortname="devwbfg"
              config={{
                identifier: meta.oldUrl ?? slug,
                title: title,
              }}
            />
```

Example found: https://mikecann.co.uk/posts/the-cube

Any ideas?

**Comment by tterb** [comment]
@mikecann It looks like this is because we're currently spreading the props that are passed to the component to allow users to specify additional attributes (className, id, etc...).
This shouldn't have any effect on the functionality, but it would probably be best to filter out the config object before passing it to the JSX element.

**Comment by mikecann** [comment]
Ah okay no worries :) Feel free to close this.
